name: arch
description: Arch portfolio
author: Francisco Panatto Miranda
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^7.1.0
  flutter_svg: ^0.22.0
  mockito: ^5.0.14

dev_dependencies:
  bloc_test: ^8.1.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/png/showcase/
    - assets/svg/images/
